name: Upload coverage reports to Codecov

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  upload-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.COVERAGE }}
